format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ionic
workflows:
  deploy:
    steps:
    - git-clone@8: {}
    - certificate-and-profile-installer@1: {}
    - npm@1:
        inputs:
        - command: install
    - karma-jasmine-runner@0: {}
    - generate-cordova-build-configuration@0: {}
    - ionic-archive@2:
        inputs:
        - platform: "$IONIC_PLATFORM"
        - target: emulator
    - deploy-to-bitrise-io@2: {}
  primary:
    steps:
    - activate-ssh-key@4: {}
    - git-clone@8: {}
    - restore-npm-cache@1: {}
    - npm@1:
        inputs:
        - command: install
        - workdir: .
    - script@1:
        inputs:
        - content: |
            # Ensure required Angular Devkit and Karma packages are installed
            npm install @angular-devkit/build-angular karma --save-dev
    - karma-jasmine-runner@0:
        inputs:
        - browsers: Chrome
    - save-npm-cache@1: {}
    - deploy-to-bitrise-io@2: {}
triggers:
  push:
  - branch: main
  pull_request:
  - source_branch: "*"
meta:
  bitrise.io:
    stack: osx-xcode-16.0.x
    machine_type_id: g2-m1.4core
app:
  envs:
  - IONIC_PLATFORM: ios
    opts:
      is_expand: false